### ISSUE TITLE
Non-quoted attribute values

### ISSUE THREAD

**Issue by activexray** [green-coder/html-to-hiccup#1]
Thanks for making this a library!

First thing I noticed is missing non-quoted attribute values.

```clj
taipei-404.html> (html->hiccup "<script src=/foo/bar/baz.js></script>")
Execution error at taipei-404.html/html->hiccup$fn (html.cljc:51).
Invalid token: /foo/bar/baz.js
```

I'd like to use this library in cybermonday - so I'm planning on stress testing it. I can get to a PR in a bit when I have some time.

**Comment by green-coder** [comment]
Thank you for the issue.

The problem came from `(edn/read-string "/foo/bar/baz.js")`. No need a PR this time, I have a fix ready.
